### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties feed.

spring:
  profiles.active: default
---
spring:
  profiles: default   # this is for local development. For QA, Production override these values

spring.jmx:
   enabled: true

spring.datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/black
    username: black
    password: mypassword

server:
  port: 8444
  ssl.key-store: keystore.p12
  ssl.key-store-password: happyinbit
  ssl.keyStoreType: PKCS12
  ssl.keyAlias: tomcat

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: black
  version: 0.1
  description: feed upload & download
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

logging.feed: /var/log/wizindia/black/backend.log
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR
